### ISSUE TITLE
Which algorithm do you use to analysis？

### ISSUE THREAD

**Issue by sunfeng90** [zoltan-nz/kafka-spark-project#1]
Hi，which analysis do you use to analysis the data？k-mens？

**Comment by zoltan-nz** [comment]
@sunfeng90 thanks for your question, but at the moment there isn't any analysis implementation...

**Comment by sunfeng90** [comment]
thanks a lot！

**Comment by sunfeng90** [comment]
I study your code these days. Do you use k-means to analysis your data?

**Comment by sunfeng90** [comment]
When i use 9092 as the port, but got these errors.

`kafka.common.KafkaException: Socket server failed to bind to localhost:9092: Address already in use.
[KAFKA]         at kafka.network.Acceptor.openServerSocket(SocketServer.scala:331)
[KAFKA]         at kafka.network.Acceptor.<init>(SocketServer.scala:256)
[KAFKA]         at kafka.network.SocketServer.$anonfun$startup$1(SocketServer.scala:98)
[KAFKA]         at kafka.network.SocketServer.$anonfun$startup$1$adapted(SocketServer.scala:89)
[KAFKA]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
[KAFKA]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
[KAFKA]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[KAFKA]         at kafka.network.SocketServer.startup(SocketServer.scala:89)
[KAFKA]         at kafka.server.KafkaServer.startup(KafkaServer.scala:229)
[KAFKA]         at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
[KAFKA]         at kafka.Kafka$.main(Kafka.scala:92)
[KAFKA]         at kafka.Kafka.main(Kafka.scala)
[KAFKA] Caused by: java.net.BindException: Address already in use
[KAFKA]         at sun.nio.ch.Net.bind0(Native Method)
[KAFKA]         at sun.nio.ch.Net.bind(Net.java:433)
[KAFKA]         at sun.nio.ch.Net.bind(Net.java:425)
[KAFKA]         at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[KAFKA]         at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[KAFKA]         at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
[KAFKA]         at kafka.network.Acceptor.openServerSocket(SocketServer.scala:327)
[KAFKA]         ... 11 more`

**Comment by sunfeng90** [comment]
I use docker in the local.I change the 9092 to 9093, but got these errors.
`/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:330
[BACKEND]         throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
[BACKEND]               ^
[BACKEND] TSError: ⨯ Unable to compile TypeScript
[BACKEND] src/controllers/data-files.controller.ts (54,18): Argument of type 'null' is not assignable to parameter of type 'Error | undefined'. (2345)
[BACKEND]     at getOutput (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:330:15)
[BACKEND]     at Object.compile (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:516:11)
[BACKEND]     at Module.m._compile (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:403:43)
[BACKEND]     at Module._extensions..js (module.js:671:10)
[BACKEND]     at Object.require.extensions.(anonymous function) [as .ts] (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:406:12)
[BACKEND]     at Module.load (module.js:573:32)
[BACKEND]     at tryModuleLoad (module.js:513:12)
[BACKEND]     at Function.Module._load (module.js:505:3)
[BACKEND]     at Module.require (module.js:604:17)
[BACKEND]     at require (internal/module.js:11:18)
[BACKEND] [nodemon] app crashed - waiting for file changes before starting...
[KAFKA] [2018-05-04 21:44:37,193] INFO Server environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT (org.apache.zookeeper.server.ZooKeeperServer)
[KAFKA] [2018-05-04 21:44:37,204] INFO Server environment:host.name=192.168.1.105 (org.apache.zookeeper.server.ZooKeeperServer)
[KAFKA] [2018-05-04 21:44:37,204] INFO Server environment:java.version=1.8.0_111 (org.apache.zookeeper.server.ZooKeeperServer)
[KAFKA] [2018-05-04 21:44:37,204] INFO Server environment:java.vendor=Oracle Corporation (org.apache.zookeeper.server.ZooKeeperServer)
[KAFKA] [2018-05-04 21:44:37,205] INFO Server environment:java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre (org.apache.zookeeper.server.ZooKeeperServer)`

**Comment by sunfeng90** [comment]
How to solve my problem? I can't run your code in the localhost.

**Comment by sunfeng90** [comment]
I  will find another project about spark、kafka and K-means.Thanks a lot .

**Comment by zoltan-nz** [comment]
@sunfeng90 Could you share the link here, please? It would be interesting for me also. :)

**Comment by sunfeng90** [comment]
OK，Thanks for your reply these days！

**Comment by zoltan-nz** [comment]
@sunfeng90 No worries. Happy to help. Could you please share the link to the other project what you found? I would check out it also. :) Thanks! :)

**Comment by sunfeng90** [comment]
Ok, I'm finding it today.If I find best one, I will share with you!
