### ISSUE TITLE
Can not the code in the local!

### ISSUE THREAD

**Issue by sunfeng90** [zoltan-nz/kafka-spark-project#3]
After I clone your code, then run `
 npm run setup
npm start`
after serverl  several minutes, output following errors.
 
`[2018-05-05 09:18:32,373] INFO Got user-level KeeperException when processing sessionid:0x1632de0e3d10000 type:delete cxid:0x52 zxid:0x29 txntype:-1 reqpath:n/a Error Path:/admin/preferred_replica_election Error:KeeperErrorCode = NoNode for /admin/preferred_replica_election (org.apache.zookeeper.server.PrepRequestProcessor)
[KAFKA] npm ERR! code ELIFECYCLE
[KAFKA] npm ERR! errno 1
[KAFKA] npm ERR! kafka-spark-project@1.0.0 start:kafka: `npm run clean:kafka && zookeeper-server-start ./kafka/config/zookeeper.properties & kafka-server-start ./kafka/config/server.properties`
npm ERR! Exit status 1
[KAFKA] npm ERR!
[KAFKA] npm ERR! Failed at the kafka-spark-project@1.0.0 start:kafka script.
[KAFKA] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[KAFKA]
[KAFKA] npm ERR! A complete log of this run can be found in:
[KAFKA] npm ERR!     /Users/sunfeng/.npm/_logs/2018-05-05T01_18_32_591Z-debug.log
[BACKEND]
[BACKEND] /Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:330
[BACKEND]         throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
[BACKEND]               ^
[BACKEND] TSError: ⨯ Unable to compile TypeScript
[BACKEND] src/controllers/data-files.controller.ts (54,18): Argument of type 'null' is not assignable to parameter of type 'Error | undefined'. (2345)
[BACKEND]     at getOutput (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:330:15)
[BACKEND]     at Object.compile (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:516:11)
[BACKEND]     at Module.m._compile (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:403:43)
[BACKEND]     at Module._extensions..js (module.js:671:10)
[BACKEND]     at Object.require.extensions.(anonymous function) [as .ts] (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:406:12)
[BACKEND]     at Module.load (module.js:573:32)
[BACKEND]     at tryModuleLoad (module.js:513:12)
[BACKEND]     at Function.Module._load (module.js:505:3)
[BACKEND]     at Module.require (module.js:604:17)
[BACKEND]     at require (internal/module.js:11:18)
[BACKEND] [nodemon] app crashed - waiting for file changes before starting...
[FRONTEND] Compiled successfully!
[FRONTEND]
[FRONTEND] You can now view frontend in the browser.
[FRONTEND]
[FRONTEND]   Local:            http://localhost:3001/
[FRONTEND]   On Your Network:  http://192.168.1.103:3001/
[FRONTEND]
[FRONTEND] Note that the development build is not optimized.
[FRONTEND] To create a production build, use npm run build.
[FRONTEND]`

http://localhost:3001/ opened in the browser, but no any data.

**Comment by zoltan-nz** [comment]
Are Kafka Installed on your Mac? 

This experiment is still heavily work in progress and not really documented... sorry.
