### ISSUE TITLE
But I cannot run in the localhost!

### ISSUE THREAD

**Issue by sunfeng90** [zoltan-nz/kafka-spark-project#4]
Yes, I installed Kafka in the Mac.I want to use your code to analysis my data as graduation.Hep me, thank!

**Comment by zoltan-nz** [comment]
How have you installed Kafka on your Mac?

**Comment by sunfeng90** [comment]
First installed by `brew install kafka`, then the kafka installed in 
`/usr/local/etc/kafka/server.properties
/usr/local/etc/kafka/zookeeper.properties`,finally start zookeeper and kafka by `zookeeper-server-start /usr/local/etc/kafka/zookeeper.properties &`  `kafka-server-start /usr/local/etc/kafka/server.properties &`

**Comment by sunfeng90** [comment]
Whent I start kafka, got these errors.
` Failed to acquire lock on file .lock in /usr/local/var/lib/kafka-logs. A Kafka instance in another process or thread is using this directory.
	at kafka.log.LogManager.$anonfun$lockLogDirs$1(LogManager.scala:234)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)` 

but I kill the instance of the port 9092 or 9093.

**Comment by sunfeng90** [comment]
I found my kafka run in the serivce before, so got `A Kafka instance in another process or thread is using this directory. at `

**Comment by sunfeng90** [comment]
I run `npm run setup` and `npm run start`,but got errors.

`/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:330
[BACKEND]         throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))[BACKEND]               ^
[BACKEND] TSError: ⨯ Unable to compile TypeScript
[BACKEND] src/controllers/data-files.controller.ts (54,18): Argument of type 'null' is not assignable to parameter of type 'Error | undefined'. (2345)
[BACKEND]     at getOutput (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:330:15)
[BACKEND]     at Object.compile (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:516:11)
[BACKEND]     at Module.m._compile (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:403:43)
[BACKEND]     at Module._extensions..js (module.js:671:10)
[BACKEND]     at Object.require.extensions.(anonymous function) [as .ts] (/Users/sunfeng/Project/Spark/kafka-spark-project/backend/node_modules/_ts-node@6.0.2@ts-node/src/index.ts:406:12)
[BACKEND]     at Module.load (module.js:573:32)
[BACKEND]     at tryModuleLoad (module.js:513:12)
[BACKEND]     at Function.Module._load (module.js:505:3)
[BACKEND]     at Module.require (module.js:604:17)
[BACKEND]     at require (internal/module.js:11:18)
[BACKEND] [nodemon] app crashed - waiting for file changes before starting...
[FRONTEND] Compiled successfully!
[FRONTEND]
[FRONTEND] You can now view frontend in the browser.
[FRONTEND]
[FRONTEND]   Local:            http://localhost:3001/
[FRONTEND]   On Your Network:  http://192.168.1.101:3001/
[FRONTEND]
[FRONTEND] Note that the development build is not optimized.
[FRONTEND] To create a production build, use npm run build.
[FRONTEND]
`

what's your version of _ts-node?

**Comment by sunfeng90** [comment]
When I run the project, I got: `Server status: Offline` in the browser of Home page.Why ?

**Comment by zoltan-nz** [comment]
* When you use `npm run start`, Zookeeper and Kafka will be launched also, so you shouldn't launch Kafka separately.  
* You should have `Node.js v8` or `v10` on your computer.

**Comment by sunfeng90** [comment]
I have NodeJs  v9.6.1

**Comment by sunfeng90** [comment]
Thanks，a lot！After I run  `npm start`， but got errors：` ERROR Error while creating ephemeral at /brokers/ids/0, node already exists and owner '72058057420832769' does not match current session '72058057420832776' (kafka.zk.KafkaZkClient$CheckedEphemeral)
[KAFKA] [2018-05-05 22:06:37,843] INFO Result of znode creation at /brokers/ids/0 is: NODEEXISTS (kafka.zk.KafkaZkClient)
[KAFKA] [2018-05-05 22:06:37,857] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
[KAFKA] org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists
[KAFKA]         at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
[KAFKA]         at kafka.zk.KafkaZkClient.checkedEphemeralCreate(KafkaZkClient.scala:1476)
[KAFKA]         at kafka.zk.KafkaZkClient.registerBrokerInZk(KafkaZkClient.scala:84)
[KAFKA]         at kafka.server.KafkaServer.startup(KafkaServer.scala:254)
[KAFKA]         at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
[KAFKA]         at kafka.Kafka$.main(Kafka.scala:92)
[KAFKA]         at kafka.Kafka.main(Kafka.scala)
[KAFKA] [2018-05-05 22:06:37,865] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[KAFKA] [2018-05-05 22:06:37,867] INFO [SocketServer brokerId=0] Stopping socket server request processors (kafka.network.SocketServer)
[KAFKA] [2018-05-05 22:06:37,922] INFO [SocketServer brokerId=0] Stopped socket server request processors (kafka.network.SocketServer)
[KAFKA] [2018-05-05 22:06:37,931] INFO [ReplicaManager broker=0] Shutting down (kafka.server.ReplicaManager)
[KAFKA] [2018-05-05 22:06:37,932] INFO [LogDirFailureHandler]: Shutting down (kafka.server.ReplicaManager$LogDirFailureHandler)
[KAFKA] [2018-05-05 22:06:37,934] INFO [LogDirFailureHandler]: Stopped (kafka.server.ReplicaManager$LogDirFailureHandler)
[KAFKA] [2018-05-05 22:06:37,935] INFO [LogDirFailureHandler]: Shutdown completed (kafka.server.ReplicaManager$LogDirFailureHandler)
[KAFKA] [2018-05-05 22:06:37,936] INFO [ReplicaFetcherManager on broker 0] shutting down (kafka.server.ReplicaFetcherManager)
[KAFKA] [2018-05-05 22:06:37,939] INFO [ReplicaFetcherManager on broker 0] shutdown completed (kafka.server.ReplicaFetcherManager)
[KAFKA] [2018-05-05 22:06:37,939] INFO [ReplicaAlterLogDirsManager on broker 0] shutting down (kafka.server.ReplicaAlterLogDirsManager)
[KAFKA] [2018-05-05 22:06:37,940] INFO [ReplicaAlterLogDirsManager on broker 0] shutdown completed (kafka.server.ReplicaAlterLogDirsManager)
[KAFKA] [2018-05-05 22:06:37,940] INFO [ExpirationReaper-0-Fetch]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,041] INFO [ExpirationReaper-0-Fetch]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,042] INFO [ExpirationReaper-0-Fetch]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,042] INFO [ExpirationReaper-0-Produce]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,238] INFO [ExpirationReaper-0-Produce]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,238] INFO [ExpirationReaper-0-Produce]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,239] INFO [ExpirationReaper-0-DeleteRecords]: Shutting down (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,246] INFO [ExpirationReaper-0-DeleteRecords]: Stopped (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,246] INFO [ExpirationReaper-0-DeleteRecords]: Shutdown completed (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[KAFKA] [2018-05-05 22:06:38,255] INFO [ReplicaManager broker=0] Shut down completely (kafka.server.ReplicaManager)
[KAFKA] [2018-05-05 22:06:38,257] INFO Shutting down. (kafka.log.LogManager)
[KAFKA] [2018-05-05 22:06:38,302] INFO Shutdown complete. (kafka.log.LogManager)
[KAFKA] [2018-05-05 22:06:38,305] INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient)
[KAFKA] [2018-05-05 22:06:38,310] INFO Session: 0x100006be3c60008 closed (org.apache.zookeeper.ZooKeeper)
[KAFKA] [2018-05-05 22:06:38,310] INFO EventThread shut down for session: 0x100006be3c60008 (org.apache.zookeeper.ClientCnxn)
[KAFKA] [2018-05-05 22:06:38,314] INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient)
[KAFKA] [2018-05-05 22:06:38,315] INFO [ThrottledRequestReaper-Fetch]: Shutting down (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:38,514] INFO [ThrottledRequestReaper-Fetch]: Stopped (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:38,514] INFO [ThrottledRequestReaper-Fetch]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:38,524] INFO [ThrottledRequestReaper-Produce]: Shutting down (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:39,518] INFO [ThrottledRequestReaper-Produce]: Stopped (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:39,518] INFO [ThrottledRequestReaper-Produce]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:39,519] INFO [ThrottledRequestReaper-Request]: Shutting down (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:39,527] INFO [ThrottledRequestReaper-Request]: Shutdown completed (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:39,527] INFO [ThrottledRequestReaper-Request]: Stopped (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[KAFKA] [2018-05-05 22:06:39,529] INFO [SocketServer brokerId=0] Shutting down socket server (kafka.network.SocketServer)
[KAFKA] [2018-05-05 22:06:39,652] INFO [SocketServer brokerId=0] Shutdown completed (kafka.network.SocketServer)
[KAFKA] [2018-05-05 22:06:39,666] INFO [KafkaServer id=0] shut down completed (kafka.server.KafkaServer)
[KAFKA] [2018-05-05 22:06:39,667] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
[KAFKA] [2018-05-05 22:06:39,677] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[KAFKA] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[KAFKA] npm ERR! kafka-spark-project@1.0.0 start:kafka: `npm run clean:kafka && zookeeper-server-start ./kafka/config/zookeeper.properties & kafka-server-start ./kafka/config/server.properties`
[KAFKA] npm ERR! Exit status 1
npm ERR!
[KAFKA] npm ERR! Failed at the kafka-spark-project@1.0.0 start:kafka script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[KAFKA]
[KAFKA] npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunfeng/.npm/_logs/2018-05-05T14_06_40_076Z-debug.log
[KAFKA] npm run start:kafka exited with code 1
--> Sending SIGTERM to other processes..
[BACKEND] npm run start:backend exited with code null
[FRONTEND] npm run start:frontend exited with code null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kafka-spark-project@1.0.0 start-if-not-start-kafka: `concurrently -k --names 'KAFKA,BACKEND,FRONTEND' 'npm run start:kafka' 'npm run start:backend' 'npm run start:frontend'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kafka-spark-project@1.0.0 start-if-not-start-kafka script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunfeng/.npm/_logs/2018-05-05T14_06_40_432Z-debug.log`

**Comment by sunfeng90** [comment]
I start Kafka separately，I got errors which means run the kafka again.But I can use Kafka.I run `npm start` stoped by errors below.

**Comment by zoltan-nz** [comment]
@sunfeng90 the actual implementation expects that you don't run Kafka separately, so it will try to run Kafka, this is why you got the error. Sorry about it.

**Comment by sunfeng90** [comment]
You are welcome! Are you a student? I'm a frontend and NodeJs backend in the work.I want to make friends with you. I study spark and kafka for my friend's graduation.

**Comment by sunfeng90** [comment]
Thanks  a lot for your reply these days.

**Comment by zoltan-nz** [comment]
The best if you guys join to https://node-js.slack.com channel. We can chat there, you can find me under the name `zoltan`.

**Comment by sunfeng90** [comment]
Ok, thanks! But I have an @freebird.com.hk, @webofwork.com, @mindbodygreen.com, @cedarville.edu, @upjers.com, @smartdev.vn, or @tripmap.me email address! I have google email address and luckyfengsun@163.com

**Comment by sunfeng90** [comment]
Could you send a invitation email to help me join it?

**Comment by zoltan-nz** [comment]
@sunfeng90 You can join to the official Node.js Slack channel here: http://www.nodeslackers.com/

**Comment by sunfeng90** [comment]
Thanks a lot! When I register this web, but don't got any invitation email.
