### ISSUE TITLE
Why i add a file.csv in the csv-storage of the backend,but no any data output in the Home page?

### ISSUE THREAD

**Issue by sunfeng90** [zoltan-nz/kafka-spark-project#5]
Hi, I add a file named file.csv in the csv-storage. there are data in the file.csv: 

`1    2    3    4    5    6    7

8    9   10    11   12   13   14` 

but there are no data in the Home page? why ? thanks!

**Comment by zoltan-nz** [comment]
Not implemented yet, you should see streaming in the console, where you launched `npm run start`... This project is WIP... The only features what we have is downloading raw csv from S3 server and after streaming, but you can see in the background only, not forwarded to the frontend at all...

**Comment by sunfeng90** [comment]
OK，I see the data in the background！
