### ISSUE TITLE
Add docker composer to run components

### ISSUE THREAD

**Issue by zoltan-nz** [zoltan-nz/kafka-spark-project#6]

**Comment by zoltan-nz** [comment]
`docker-compose.yml` is added to the project and we can run it with `docker-compose up`.

https://github.com/zoltan-nz/kafka-spark-project/blob/master/docker-compose.yml

**Comment by WindyStu** [comment]
after code 'docker-compose up',console shows the errors that 'ERROR: Service 'backend' failed to build : Build failed‘
In backend dockfile ,the code 'COPY ./dist ./dist:' fail to find. what should i do to overcome this issue?
